### ISSUE TITLE
The function "utils. choose_threshold" is missing

### ISSUE THREAD

**Issue by zzukun** [rpmcruz/dm#2]
Hi,
I am learning your implement of GBrank algorithm in ensemble,
link: https://github.com/rpmcruz/machine-learning/blob/d103e4e6f6cbf67924fa930ec568a79b986c3d99/ensemble/boosting/gbrank.py

But i can't find the utils module & the choose_threshold function,
I want to know the details of func choose_threshold, thanks!

Best wishes

**Comment by rpmcruz** [comment]
Hi Kun Li,
The reason why those functions don't exist is because we have implemented GBRank while doing some experiments to adapt pairwise ranking methods for classification (see [our publication](http://ieeexplore.ieee.org/abstract/document/7727469/)).
Please give me a dataset example, and I will get it to work for you.
Best regards

**Comment by zzukun** [comment]
OK, I understood, thank you very much!
Regards.
